export const MOBILE_CHANGED = 'MOBILE_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const USER_REGISTER_ATTEMP = 'USER_REGISTER_ATTEMP';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
